[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --strict-markers --alluredir=allure-results
log_cli = true
log_cli_level = INFO
log_file = test_run.log
log_file_level = DEBUG
log_file_format = %(asctime)s %(levelname)s %(name)s: %(message)s
markers =
    smoke: быстрые смоук-тесты
    api: тесты API эндпоинтов
    regression: регрессия
    positive: позитивный тест (валидные данные, ожидаем успех)
    negative: негативный тест (отклонения от задуманного, ожидаем ошибку)
    mock: тест на заглушках (реальный API не вызывается)
